# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - run: nix run .#west -- init -m https://github.com/zephyrproject-rtos/zephyr
      - run: nix run .#west -- update
      - run: nix run .#west -- build -b wio_terminal -p always zephyr/samples/basic/blinky 

