# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-sample:
    strategy:
      fail-fast: false
      matrix:
        board: [wio_terminal, m5stack_core2]
        target: [basic/blinky]
        builder: [.#west]
        include:
          - board: [wio_terminal]
            target: [basic/blinky]
            builder: [.#west-arm]

    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - run: |
          nix run .#west -- init -m https://github.com/zephyrproject-rtos/zephyr
          nix run .#west -- update
      - run: nix run ${{ matrix.builder }} -- build -b ${{ matrix.board }} -p always  zephyr/samples/${{ matrix.target }}

